version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1821
      POSTGRES_DB: postgres
    ports:
      - "5432:5433"

  backend:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 1821
      DB_NAME: message_postgres