// Code generated by ent, DO NOT EDIT.

package board

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the board type in the database.
	Label = "board"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldBoardName holds the string denoting the board_name field in the database.
	FieldBoardName = "board_name"
	// FieldBoardAdmin holds the string denoting the board_admin field in the database.
	FieldBoardAdmin = "board_admin"
	// FieldBoardPassword holds the string denoting the board_password field in the database.
	FieldBoardPassword = "board_password"
	// FieldBoardStar holds the string denoting the board_star field in the database.
	FieldBoardStar = "board_star"
	// FieldCreatedAt holds the string denoting the createdat field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updatedat field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeMessages holds the string denoting the messages edge name in mutations.
	EdgeMessages = "messages"
	// Table holds the table name of the board in the database.
	Table = "boards"
	// MessagesTable is the table that holds the messages relation/edge.
	MessagesTable = "messages"
	// MessagesInverseTable is the table name for the Message entity.
	// It exists in this package in order to avoid circular dependency with the "message" package.
	MessagesInverseTable = "messages"
	// MessagesColumn is the table column denoting the messages relation/edge.
	MessagesColumn = "board_messages"
)

// Columns holds all SQL columns for board fields.
var Columns = []string{
	FieldID,
	FieldBoardName,
	FieldBoardAdmin,
	FieldBoardPassword,
	FieldBoardStar,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultBoardName holds the default value on creation for the "board_name" field.
	DefaultBoardName string
	// DefaultBoardAdmin holds the default value on creation for the "board_admin" field.
	DefaultBoardAdmin string
	// DefaultBoardPassword holds the default value on creation for the "board_password" field.
	DefaultBoardPassword string
	// DefaultBoardStar holds the default value on creation for the "board_star" field.
	DefaultBoardStar int
	// DefaultCreatedAt holds the default value on creation for the "createdAt" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updatedAt" field.
	DefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Board queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBoardName orders the results by the board_name field.
func ByBoardName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBoardName, opts...).ToFunc()
}

// ByBoardAdmin orders the results by the board_admin field.
func ByBoardAdmin(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBoardAdmin, opts...).ToFunc()
}

// ByBoardPassword orders the results by the board_password field.
func ByBoardPassword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBoardPassword, opts...).ToFunc()
}

// ByBoardStar orders the results by the board_star field.
func ByBoardStar(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBoardStar, opts...).ToFunc()
}

// ByCreatedAt orders the results by the createdAt field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updatedAt field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByMessagesCount orders the results by messages count.
func ByMessagesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMessagesStep(), opts...)
	}
}

// ByMessages orders the results by messages terms.
func ByMessages(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMessagesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newMessagesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MessagesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, MessagesTable, MessagesColumn),
	)
}
