// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/ddr4869/msazoom/chat-service/ent/chat"
	"github.com/ddr4869/msazoom/chat-service/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	chatFields := schema.Chat{}.Fields()
	_ = chatFields
	// chatDescChatName is the schema descriptor for chat_name field.
	chatDescChatName := chatFields[0].Descriptor()
	// chat.DefaultChatName holds the default value on creation for the chat_name field.
	chat.DefaultChatName = chatDescChatName.Default.(string)
	// chatDescChatUser is the schema descriptor for chat_user field.
	chatDescChatUser := chatFields[1].Descriptor()
	// chat.DefaultChatUser holds the default value on creation for the chat_user field.
	chat.DefaultChatUser = chatDescChatUser.Default.(string)
	// chatDescCreatedAt is the schema descriptor for createdAt field.
	chatDescCreatedAt := chatFields[3].Descriptor()
	// chat.DefaultCreatedAt holds the default value on creation for the createdAt field.
	chat.DefaultCreatedAt = chatDescCreatedAt.Default.(func() time.Time)
	// chatDescUpdatedAt is the schema descriptor for updatedAt field.
	chatDescUpdatedAt := chatFields[4].Descriptor()
	// chat.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	chat.DefaultUpdatedAt = chatDescUpdatedAt.Default.(func() time.Time)
}
