// Code generated by ent, DO NOT EDIT.

package friend

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/ddr4869/msazoom/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Friend {
	return predicate.Friend(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Friend {
	return predicate.Friend(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Friend {
	return predicate.Friend(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Friend {
	return predicate.Friend(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Friend {
	return predicate.Friend(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Friend {
	return predicate.Friend(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Friend {
	return predicate.Friend(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Friend {
	return predicate.Friend(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Friend {
	return predicate.Friend(sql.FieldLTE(FieldID, id))
}

// Username applies equality check predicate on the "username" field. It's identical to UsernameEQ.
func Username(v string) predicate.Friend {
	return predicate.Friend(sql.FieldEQ(FieldUsername, v))
}

// Friend applies equality check predicate on the "friend" field. It's identical to FriendEQ.
func Friend(v string) predicate.Friend {
	return predicate.Friend(sql.FieldEQ(FieldFriend, v))
}

// CreatedAt applies equality check predicate on the "createdAt" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Friend {
	return predicate.Friend(sql.FieldEQ(FieldCreatedAt, v))
}

// UsernameEQ applies the EQ predicate on the "username" field.
func UsernameEQ(v string) predicate.Friend {
	return predicate.Friend(sql.FieldEQ(FieldUsername, v))
}

// UsernameNEQ applies the NEQ predicate on the "username" field.
func UsernameNEQ(v string) predicate.Friend {
	return predicate.Friend(sql.FieldNEQ(FieldUsername, v))
}

// UsernameIn applies the In predicate on the "username" field.
func UsernameIn(vs ...string) predicate.Friend {
	return predicate.Friend(sql.FieldIn(FieldUsername, vs...))
}

// UsernameNotIn applies the NotIn predicate on the "username" field.
func UsernameNotIn(vs ...string) predicate.Friend {
	return predicate.Friend(sql.FieldNotIn(FieldUsername, vs...))
}

// UsernameGT applies the GT predicate on the "username" field.
func UsernameGT(v string) predicate.Friend {
	return predicate.Friend(sql.FieldGT(FieldUsername, v))
}

// UsernameGTE applies the GTE predicate on the "username" field.
func UsernameGTE(v string) predicate.Friend {
	return predicate.Friend(sql.FieldGTE(FieldUsername, v))
}

// UsernameLT applies the LT predicate on the "username" field.
func UsernameLT(v string) predicate.Friend {
	return predicate.Friend(sql.FieldLT(FieldUsername, v))
}

// UsernameLTE applies the LTE predicate on the "username" field.
func UsernameLTE(v string) predicate.Friend {
	return predicate.Friend(sql.FieldLTE(FieldUsername, v))
}

// UsernameContains applies the Contains predicate on the "username" field.
func UsernameContains(v string) predicate.Friend {
	return predicate.Friend(sql.FieldContains(FieldUsername, v))
}

// UsernameHasPrefix applies the HasPrefix predicate on the "username" field.
func UsernameHasPrefix(v string) predicate.Friend {
	return predicate.Friend(sql.FieldHasPrefix(FieldUsername, v))
}

// UsernameHasSuffix applies the HasSuffix predicate on the "username" field.
func UsernameHasSuffix(v string) predicate.Friend {
	return predicate.Friend(sql.FieldHasSuffix(FieldUsername, v))
}

// UsernameEqualFold applies the EqualFold predicate on the "username" field.
func UsernameEqualFold(v string) predicate.Friend {
	return predicate.Friend(sql.FieldEqualFold(FieldUsername, v))
}

// UsernameContainsFold applies the ContainsFold predicate on the "username" field.
func UsernameContainsFold(v string) predicate.Friend {
	return predicate.Friend(sql.FieldContainsFold(FieldUsername, v))
}

// FriendEQ applies the EQ predicate on the "friend" field.
func FriendEQ(v string) predicate.Friend {
	return predicate.Friend(sql.FieldEQ(FieldFriend, v))
}

// FriendNEQ applies the NEQ predicate on the "friend" field.
func FriendNEQ(v string) predicate.Friend {
	return predicate.Friend(sql.FieldNEQ(FieldFriend, v))
}

// FriendIn applies the In predicate on the "friend" field.
func FriendIn(vs ...string) predicate.Friend {
	return predicate.Friend(sql.FieldIn(FieldFriend, vs...))
}

// FriendNotIn applies the NotIn predicate on the "friend" field.
func FriendNotIn(vs ...string) predicate.Friend {
	return predicate.Friend(sql.FieldNotIn(FieldFriend, vs...))
}

// FriendGT applies the GT predicate on the "friend" field.
func FriendGT(v string) predicate.Friend {
	return predicate.Friend(sql.FieldGT(FieldFriend, v))
}

// FriendGTE applies the GTE predicate on the "friend" field.
func FriendGTE(v string) predicate.Friend {
	return predicate.Friend(sql.FieldGTE(FieldFriend, v))
}

// FriendLT applies the LT predicate on the "friend" field.
func FriendLT(v string) predicate.Friend {
	return predicate.Friend(sql.FieldLT(FieldFriend, v))
}

// FriendLTE applies the LTE predicate on the "friend" field.
func FriendLTE(v string) predicate.Friend {
	return predicate.Friend(sql.FieldLTE(FieldFriend, v))
}

// FriendContains applies the Contains predicate on the "friend" field.
func FriendContains(v string) predicate.Friend {
	return predicate.Friend(sql.FieldContains(FieldFriend, v))
}

// FriendHasPrefix applies the HasPrefix predicate on the "friend" field.
func FriendHasPrefix(v string) predicate.Friend {
	return predicate.Friend(sql.FieldHasPrefix(FieldFriend, v))
}

// FriendHasSuffix applies the HasSuffix predicate on the "friend" field.
func FriendHasSuffix(v string) predicate.Friend {
	return predicate.Friend(sql.FieldHasSuffix(FieldFriend, v))
}

// FriendEqualFold applies the EqualFold predicate on the "friend" field.
func FriendEqualFold(v string) predicate.Friend {
	return predicate.Friend(sql.FieldEqualFold(FieldFriend, v))
}

// FriendContainsFold applies the ContainsFold predicate on the "friend" field.
func FriendContainsFold(v string) predicate.Friend {
	return predicate.Friend(sql.FieldContainsFold(FieldFriend, v))
}

// CreatedAtEQ applies the EQ predicate on the "createdAt" field.
func CreatedAtEQ(v time.Time) predicate.Friend {
	return predicate.Friend(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "createdAt" field.
func CreatedAtNEQ(v time.Time) predicate.Friend {
	return predicate.Friend(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "createdAt" field.
func CreatedAtIn(vs ...time.Time) predicate.Friend {
	return predicate.Friend(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "createdAt" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Friend {
	return predicate.Friend(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "createdAt" field.
func CreatedAtGT(v time.Time) predicate.Friend {
	return predicate.Friend(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "createdAt" field.
func CreatedAtGTE(v time.Time) predicate.Friend {
	return predicate.Friend(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "createdAt" field.
func CreatedAtLT(v time.Time) predicate.Friend {
	return predicate.Friend(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "createdAt" field.
func CreatedAtLTE(v time.Time) predicate.Friend {
	return predicate.Friend(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Friend) predicate.Friend {
	return predicate.Friend(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Friend) predicate.Friend {
	return predicate.Friend(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Friend) predicate.Friend {
	return predicate.Friend(sql.NotPredicates(p))
}
