// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ddr4869/msazoom/ent/hotboard"
)

// HotBoardCreate is the builder for creating a HotBoard entity.
type HotBoardCreate struct {
	config
	mutation *HotBoardMutation
	hooks    []Hook
}

// Mutation returns the HotBoardMutation object of the builder.
func (hbc *HotBoardCreate) Mutation() *HotBoardMutation {
	return hbc.mutation
}

// Save creates the HotBoard in the database.
func (hbc *HotBoardCreate) Save(ctx context.Context) (*HotBoard, error) {
	return withHooks(ctx, hbc.sqlSave, hbc.mutation, hbc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (hbc *HotBoardCreate) SaveX(ctx context.Context) *HotBoard {
	v, err := hbc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (hbc *HotBoardCreate) Exec(ctx context.Context) error {
	_, err := hbc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hbc *HotBoardCreate) ExecX(ctx context.Context) {
	if err := hbc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (hbc *HotBoardCreate) check() error {
	return nil
}

func (hbc *HotBoardCreate) sqlSave(ctx context.Context) (*HotBoard, error) {
	if err := hbc.check(); err != nil {
		return nil, err
	}
	_node, _spec := hbc.createSpec()
	if err := sqlgraph.CreateNode(ctx, hbc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	hbc.mutation.id = &_node.ID
	hbc.mutation.done = true
	return _node, nil
}

func (hbc *HotBoardCreate) createSpec() (*HotBoard, *sqlgraph.CreateSpec) {
	var (
		_node = &HotBoard{config: hbc.config}
		_spec = sqlgraph.NewCreateSpec(hotboard.Table, sqlgraph.NewFieldSpec(hotboard.FieldID, field.TypeInt))
	)
	return _node, _spec
}

// HotBoardCreateBulk is the builder for creating many HotBoard entities in bulk.
type HotBoardCreateBulk struct {
	config
	err      error
	builders []*HotBoardCreate
}

// Save creates the HotBoard entities in the database.
func (hbcb *HotBoardCreateBulk) Save(ctx context.Context) ([]*HotBoard, error) {
	if hbcb.err != nil {
		return nil, hbcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(hbcb.builders))
	nodes := make([]*HotBoard, len(hbcb.builders))
	mutators := make([]Mutator, len(hbcb.builders))
	for i := range hbcb.builders {
		func(i int, root context.Context) {
			builder := hbcb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*HotBoardMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, hbcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, hbcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, hbcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (hbcb *HotBoardCreateBulk) SaveX(ctx context.Context) []*HotBoard {
	v, err := hbcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (hbcb *HotBoardCreateBulk) Exec(ctx context.Context) error {
	_, err := hbcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (hbcb *HotBoardCreateBulk) ExecX(ctx context.Context) {
	if err := hbcb.Exec(ctx); err != nil {
		panic(err)
	}
}
