// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/ddr4869/msazoom/ent/hotboard"
)

// HotBoard is the model entity for the HotBoard schema.
type HotBoard struct {
	config
	// ID of the ent.
	ID           int `json:"id,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*HotBoard) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case hotboard.FieldID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the HotBoard fields.
func (hb *HotBoard) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case hotboard.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			hb.ID = int(value.Int64)
		default:
			hb.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the HotBoard.
// This includes values selected through modifiers, order, etc.
func (hb *HotBoard) Value(name string) (ent.Value, error) {
	return hb.selectValues.Get(name)
}

// Update returns a builder for updating this HotBoard.
// Note that you need to call HotBoard.Unwrap() before calling this method if this HotBoard
// was returned from a transaction, and the transaction was committed or rolled back.
func (hb *HotBoard) Update() *HotBoardUpdateOne {
	return NewHotBoardClient(hb.config).UpdateOne(hb)
}

// Unwrap unwraps the HotBoard entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (hb *HotBoard) Unwrap() *HotBoard {
	_tx, ok := hb.config.driver.(*txDriver)
	if !ok {
		panic("ent: HotBoard is not a transactional entity")
	}
	hb.config.driver = _tx.drv
	return hb
}

// String implements the fmt.Stringer.
func (hb *HotBoard) String() string {
	var builder strings.Builder
	builder.WriteString("HotBoard(")
	builder.WriteString(fmt.Sprintf("id=%v", hb.ID))
	builder.WriteByte(')')
	return builder.String()
}

// HotBoards is a parsable slice of HotBoard.
type HotBoards []*HotBoard
