// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/ddr4869/msazoom/ent/board"
	"github.com/ddr4869/msazoom/ent/chat"
	"github.com/ddr4869/msazoom/ent/message"
	"github.com/ddr4869/msazoom/ent/schema"
	"github.com/ddr4869/msazoom/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	boardFields := schema.Board{}.Fields()
	_ = boardFields
	// boardDescBoardName is the schema descriptor for board_name field.
	boardDescBoardName := boardFields[0].Descriptor()
	// board.DefaultBoardName holds the default value on creation for the board_name field.
	board.DefaultBoardName = boardDescBoardName.Default.(string)
	// boardDescBoardAdmin is the schema descriptor for board_admin field.
	boardDescBoardAdmin := boardFields[1].Descriptor()
	// board.DefaultBoardAdmin holds the default value on creation for the board_admin field.
	board.DefaultBoardAdmin = boardDescBoardAdmin.Default.(string)
	// boardDescBoardPassword is the schema descriptor for board_password field.
	boardDescBoardPassword := boardFields[2].Descriptor()
	// board.DefaultBoardPassword holds the default value on creation for the board_password field.
	board.DefaultBoardPassword = boardDescBoardPassword.Default.(string)
	// boardDescBoardStar is the schema descriptor for board_star field.
	boardDescBoardStar := boardFields[3].Descriptor()
	// board.DefaultBoardStar holds the default value on creation for the board_star field.
	board.DefaultBoardStar = boardDescBoardStar.Default.(int)
	// boardDescCreatedAt is the schema descriptor for createdAt field.
	boardDescCreatedAt := boardFields[4].Descriptor()
	// board.DefaultCreatedAt holds the default value on creation for the createdAt field.
	board.DefaultCreatedAt = boardDescCreatedAt.Default.(func() time.Time)
	// boardDescUpdatedAt is the schema descriptor for updatedAt field.
	boardDescUpdatedAt := boardFields[5].Descriptor()
	// board.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	board.DefaultUpdatedAt = boardDescUpdatedAt.Default.(func() time.Time)
	chatFields := schema.Chat{}.Fields()
	_ = chatFields
	// chatDescChatName is the schema descriptor for chat_name field.
	chatDescChatName := chatFields[0].Descriptor()
	// chat.DefaultChatName holds the default value on creation for the chat_name field.
	chat.DefaultChatName = chatDescChatName.Default.(string)
	// chatDescChatUser is the schema descriptor for chat_user field.
	chatDescChatUser := chatFields[1].Descriptor()
	// chat.DefaultChatUser holds the default value on creation for the chat_user field.
	chat.DefaultChatUser = chatDescChatUser.Default.(string)
	// chatDescCreatedAt is the schema descriptor for createdAt field.
	chatDescCreatedAt := chatFields[2].Descriptor()
	// chat.DefaultCreatedAt holds the default value on creation for the createdAt field.
	chat.DefaultCreatedAt = chatDescCreatedAt.Default.(func() time.Time)
	// chatDescUpdatedAt is the schema descriptor for updatedAt field.
	chatDescUpdatedAt := chatFields[3].Descriptor()
	// chat.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	chat.DefaultUpdatedAt = chatDescUpdatedAt.Default.(func() time.Time)
	messageFields := schema.Message{}.Fields()
	_ = messageFields
	// messageDescCreatedAt is the schema descriptor for createdAt field.
	messageDescCreatedAt := messageFields[3].Descriptor()
	// message.DefaultCreatedAt holds the default value on creation for the createdAt field.
	message.DefaultCreatedAt = messageDescCreatedAt.Default.(func() time.Time)
	// messageDescUpdatedAt is the schema descriptor for updatedAt field.
	messageDescUpdatedAt := messageFields[4].Descriptor()
	// message.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	message.DefaultUpdatedAt = messageDescUpdatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescRole is the schema descriptor for role field.
	userDescRole := userFields[2].Descriptor()
	// user.DefaultRole holds the default value on creation for the role field.
	user.DefaultRole = userDescRole.Default.(int)
	// userDescCreatedAt is the schema descriptor for createdAt field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the createdAt field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updatedAt field.
	userDescUpdatedAt := userFields[4].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
}
