// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/ddr4869/msazoom/message-service/ent/message"
	"github.com/ddr4869/msazoom/message-service/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	messageFields := schema.Message{}.Fields()
	_ = messageFields
	// messageDescCreatedAt is the schema descriptor for createdAt field.
	messageDescCreatedAt := messageFields[4].Descriptor()
	// message.DefaultCreatedAt holds the default value on creation for the createdAt field.
	message.DefaultCreatedAt = messageDescCreatedAt.Default.(func() time.Time)
	// messageDescUpdatedAt is the schema descriptor for updatedAt field.
	messageDescUpdatedAt := messageFields[5].Descriptor()
	// message.DefaultUpdatedAt holds the default value on creation for the updatedAt field.
	message.DefaultUpdatedAt = messageDescUpdatedAt.Default.(func() time.Time)
}
