// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Board is the predicate function for board builders.
type Board func(*sql.Selector)

// Chat is the predicate function for chat builders.
type Chat func(*sql.Selector)

// Friend is the predicate function for friend builders.
type Friend func(*sql.Selector)

// HotBoard is the predicate function for hotboard builders.
type HotBoard func(*sql.Selector)

// Message is the predicate function for message builders.
type Message func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
